services:
  db:
    build: ./db
    container_name: db
    restart: always
    env_file:
      - ./db/.env
    networks:
      - app_network
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/insert.sql:/docker-entrypoint-initdb.d/insert.sql
      - /etc/passwd:/etc/poasswd:ro
      - /etc/group:/etc/group:ro
    user: "1000:1000"

  gps_tracker:
    build: ./src/gps_tracker
    container_name: gps_tracker
    # restart: always
    env_file:
      - ./src/gps_tracker/.env
    # depends_on:
    #   - db
    networks:
      - app_network
    volumes:
      - /home/nishimuraippei/ClassAttendTracker/src/gps_tracker/.pyicloud:/app/.pyicloud
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  attendance_checker:
    build: ./src/attendance_checker
    container_name: attendance_checker
    # restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/class_attendance
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    