services:
  db:
    build: ./db
    container_name: db
    restart: always
    env_file:
      - ./db/.env
    networks:
      - app_network
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data

  gps_tracker:
    build: ./src/gps_tracker
    container_name: gps_tracker
    # restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/class_attendance
    depends_on:
      - db
    networks:
      - app_network

  attendance_checker:
    build: ./src/attendance_checker
    container_name: attendance_checker
    # restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/class_attendance
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    